name: py38_mre
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2020.11.8=ha878542_0
  - certifi=2020.11.8=py38h578d9bd_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libgomp=9.3.0=h5dbcf3e_17
  - liblapack=3.9.0=2_openblas
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - ncurses=6.2=h58526e2_3
  - numpy=1.19.4=py38hf0fd68c_1
  - openssl=1.1.1h=h516909a_0
  - pandas=1.1.4=py38h0ef3d22_0
  - pip=20.2.4=py_0
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - readline=8.0=he28a2e2_2
  - scipy=1.5.3=py38hb2138dd_0
  - setuptools=49.6.0=py38h924ce5b_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_1
  - tk=8.6.10=hed695b0_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
prefix: /home/phnx/miniconda3/envs/py38_mre
